# This file can be used to create an environment with specific dependencies by running
#
# $conda env create -f environment.yml
#
# in the Anaconda Prompt

# Name of the environment
name: Qlunc_Env
# Dependencies we want to install
dependencies:
  - matplotlib==3.8.0
  - numpy==1.26.2 
  - yaml==0.2.5
  - scipy==1.11.4
  - spyder==4.2.1
  - python==3.11.5
  - termcolor==1.1.0
  - setuptools==68.0.0
  - math
  - sys
  - os
  - itertools
  - pickle
  - tkinter
  - customtkinter==5.2.1
  - termcolor
 

